### ISSUE TITLE
adding injectTapEventPlugin() break my hot-reload setup

### ISSUE THREAD

**Issue by sulliwane** [zilverline/react-tap-event-plugin#61]
After I add this:
```javascript
import injectTapEventPlugin from 'react-tap-event-plugin';

// Needed for onTouchTap
// Can go away when react 1.0 release
// Check this repo:
// https://github.com/zilverline/react-tap-event-plugin
injectTapEventPlugin();
```
Both of my hot reload setup don't "hot reload" anymore:
- https://github.com/mxstbr/react-boilerplate
- https://github.com/kriasoft/react-starter-kit

If I remove it, then my changes on save are hot-reloaded in the browser (without the need to refresh the page).

any ideas?

thanks.

**Comment by diegoaguilar** [comment]
@sulliwane did you solve or figured out about this?

**Comment by julienvincent** [comment]
just wrap in a try catch :D

**Comment by madjam002** [comment]
I've tried to reproduce this, do you get any other errors in the console output?

**Comment by julienvincent** [comment]
I only received the error while using jspm's hot reloader, not webpack. I have the environment that was producing the error on hand, but this is the code that produced it:

```javascript
  alreadyInjected = true;

  require('react/lib/EventPluginHub').injection.injectEventPluginsByName({
    'TapEventPlugin':       require('./TapEventPlugin.js')(shouldRejectClick)
  });
```

[Here is the blob](https://github.com/zilverline/react-tap-event-plugin/blob/master/src/injectTapEventPlugin.js#L23)

Hope that helps.

**Comment by peteruithoven** [comment]
How I'm doing this with the SystemJS hot reloader: 
``` javascript
import getHotReloadStore from 'systemjs-hot-reloader-store';
const hotStore = getHotReloadStore('myproject:index'); // store for state over hot reloads

if (!hotStore.tabInjected) {
  injectTapEventPlugin();
  hotStore.tabInjected = true;
}
```

**Comment by julienvincent** [comment]
That is definitely a cleaner way of doing it. Can I just point out you wrote hotStore.ta**b**Injected instead of hotStore.ta**p**Injected. Sorry - just my OCD acting up ;)

**Comment by diegoaguilar** [comment]
@julienvincent I'm a bit confused, any way to use `injectTabEventPlugin` and still get webpack's hot reload working? I generally use ES6 module imports.

**Comment by julienvincent** [comment]
@diegoaguilar I have never experienced any issues with webpack hot-reloading and this plugin. What would be helpful in finding the issue is creating a bare, minima repo that uses the latest webpack, babel (or whatever your transpiler is) and injectTabEventPlugin.

**Comment by julienvincent** [comment]
If said repo still fires the error you are experiencing, then link it here

**Comment by peteruithoven** [comment]
@julienvincent Thanks, fixed it.

**Comment by amalahussein** [comment]
hi guys--wondering if there is: 

A) Consensus on a workaround for this
B) If there is a fix for this now?

Thanks! 

cc @guybedford

**Comment by extonec** [comment]
`
import injectTapEventPlugin from 'react-tap-event-plugin';

class App extends Component {
  componentWillMount() {
    injectTapEventPlugin();
  }
}
`

**Comment by natdm** [comment]
@extonec - that still gives me the same issue. Strange that it works for you.

```jsx
class App extends Component {
	componentWillMount() {
		// Needed for onTouchTap 
		// http://stackoverflow.com/a/34015469/988941 
		injectTapEventPlugin()
	}

	render() {
		return (
			<Provider store={store}>
				<MuiThemeProvider>
					<Router history={browserHistory}>
						{routes}
					</Router>
				</MuiThemeProvider>
			</Provider>
		)
	}
}

const render = () => {ReactDOM.render(<App />, document.getElementById('app'))};
store.subscribe(render);
store.subscribe(() => console.log(store.getState()))
render();
```

Yields:

```
bundle.js:1710 [HMR] Cannot check for update (Full reload needed)handleError @ bundle.js:1710applyCallback @ bundle.js:1640hotApply @ bundle.js:526cb @ bundle.js:1647hotUpdateDownloaded @ bundle.js:310hotAddUpdateChunk @ bundle.js:282webpackHotUpdateCallback @ bundle.js:4(anonymous function) @ 0.8cd3b21….hot-update.js:1
bundle.js:1711 [HMR] Invariant Violation: injectTapEventPlugin(): Can only be called once per application lifecycle.

	It is recommended to call injectTapEventPlugin() just before you call 	ReactDOM.render(). If you are using an external library which calls injectTapEventPlugin() 	itself, please contact the maintainer as it shouldn't be called in library code and 	should be injected by the application.
    at invariant (http://localhost:3001/static/bundle.js:30063:16)
    at injectTapEventPlugin (http://localhost:3001/static/bundle.js:30003:6)
    at App.componentWillMount (http://localhost:3001/static/bundle.js:1844:39)
    at http://localhost:3001/static/bundle.js:17272:24
    at measureLifeCyclePerf (http://localhost:3001/static/bundle.js:16999:13)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:3001/static/bundle.js:17271:10)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:3001/static/bundle.js:17182:22)
    at Object.mountComponent (http://localhost:3001/static/bundle.js:9752:36)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:3001/static/bundle.js:17295:35)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:3001/static/bundle.js:17182:22)
```

**Comment by peteruithoven** [comment]
```
injectTapEventPlugin(): Can only be called once per application lifecycle
```
Let's the story, the place you're calling it causes it to be called multiple times. 

We moved the injection into a separate module, since this module doesn't change it's never reimported and therefore only executed once. 
``` js
import injectTapEventPlugin from 'react-tap-event-plugin';

// Needed for onTouchTap
// http://stackoverflow.com/a/34015469/988941
// Used by Material-ui
injectTapEventPlugin();
```

**Comment by Gabber** [comment]
Sorry maybe is me, but I've react 15.5.4 and react-tap-event-plugin 2.0.1, and i suffer the same error where i've to call injectTapEventPlugin()?

**Comment by olyakostuik** [comment]
@Gabber 
It is recommended to call injectTapEventPlugin() just before you call ReactDOM.render().
1.Find  ReactDOM.render() in your code
2.Put injectTapEventPlugin() on top of render() method.

**Comment by ralexand56** [comment]
Putting it next to my render method doesn't work for me. Why does this happen in the first place?

**Comment by creeperyang** [comment]
Seems my pr will solve it.

See <https://github.com/zilverline/react-tap-event-plugin/pull/106> for details.

**Comment by kfern** [comment]
@creeperyang PR #106  is open with error "This branch has conflicts that must be resolved"
Conflicting files:
src/injectTapEventPlugin.js

**Comment by creeperyang** [comment]
@kfern Just long time after I opened my pr.
